// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOLYwMO-f0EZh5hnLJOH0Ox5XcfQDA6c',
    // Must match android/app/google-services.json (mobilesdk_app_id)
    appId: '1:203321032277:android:3365ae3434348a9e8cdedc',
    messagingSenderId: '203321032277',
    projectId: 'altyazi-ceviri-editor',
    storageBucket: 'altyazi-ceviri-editor.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVwUr3JKv1ZWxOpc_B9uH262oRwBMtp-s',
    appId: '1:203321032277:web:9c8451dcc4cd9c2f8cdedc',
    messagingSenderId: '203321032277',
    projectId: 'altyazi-ceviri-editor',
    authDomain: 'altyazi-ceviri-editor.firebaseapp.com',
    storageBucket: 'altyazi-ceviri-editor.firebasestorage.app',
    measurementId: 'G-K07G6MCW8Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFb7PCpp0u7ufeDy3e62UtypIoDO2ukRM',
    appId: '1:203321032277:ios:0e047616ed0a9d538cdedc',
    messagingSenderId: '203321032277',
    projectId: 'altyazi-ceviri-editor',
    storageBucket: 'altyazi-ceviri-editor.firebasestorage.app',
    iosBundleId: 'com.example.altyaziEditoru',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFb7PCpp0u7ufeDy3e62UtypIoDO2ukRM',
    appId: '1:203321032277:ios:0e047616ed0a9d538cdedc',
    messagingSenderId: '203321032277',
    projectId: 'altyazi-ceviri-editor',
    storageBucket: 'altyazi-ceviri-editor.firebasestorage.app',
    iosBundleId: 'com.example.altyaziEditoru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVwUr3JKv1ZWxOpc_B9uH262oRwBMtp-s',
    appId: '1:203321032277:web:3e912f844ef3d01d8cdedc',
    messagingSenderId: '203321032277',
    projectId: 'altyazi-ceviri-editor',
    authDomain: 'altyazi-ceviri-editor.firebaseapp.com',
    storageBucket: 'altyazi-ceviri-editor.firebasestorage.app',
    measurementId: 'G-CFLJCRHSBZ',
  );

}