name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          changelog-types: |
            [
              {"type": "feat", "section": "Yeni Özellikler"},
              {"type": "fix", "section": "Hata Düzeltmeleri"},
              {"type": "chore", "section": "Diğer Değişiklikler"},
              {"type": "docs", "section": "Dokümantasyon"},
              {"type": "perf", "section": "Performans"},
              {"type": "refactor", "section": "Refactor"}
            ]
